### ISSUE TITLE
Marker is not displayed after granting permissions.

### ISSUE THREAD

**Issue by codefluencer** [appoly/ARCore-Location#14]
Hi, so I'm facing a weird problem and not sure if it is the library or my code. So the thing is, I am initializing location scene in a fragment. It works like a charm during the first launch when I'm asked to allow camera and location permissions, but the thing is, when I launch the app again (with granted permissions), my location marker is just not displayed anymore although all the AR planes are tracked and camera is working.

**Comment by johnwedgbury** [comment]
Hi @codefluencer - could you possibly email me with your code so I can investigate? Thanks

**Comment by codefluencer** [comment]
`System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'double android.location.Location.getLatitude()' on a null object reference
                  at uk.co.appoly.arcorelocation.LocationScene.refreshAnchorsIfRequired(LocationScene.java:137)
                  at uk.co.appoly.arcorelocation.LocationScene.processFrame(LocationScene.java:117)
                  at uk.co.appoly.sceneform_example.LocationActivity.lambda$onCreate$1$LocationActivity(LocationActivity.java:164)
                  at uk.co.appoly.sceneform_example.LocationActivity$$Lambda$1.onUpdate(Unknown Source)
                  at com.google.ar.sceneform.Scene.dispatchUpdate(Unknown Source)
W/System.err:     at com.google.ar.sceneform.SceneView.doFrame(Unknown Source)
                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:925)
                  at android.view.Choreographer.doCallbacks(Choreographer.java:702)
                  at android.view.Choreographer.doFrame(Choreographer.java:635)
                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
                  at android.os.Handler.handleCallback(Handler.java:751)
                  at android.os.Handler.dispatchMessage(Handler.java:95)
                  at android.os.Looper.loop(Looper.java:154)
                  at android.app.ActivityThread.main(ActivityThread.java:6692)
                  at java.lang.reflect.Method.invoke(Native Method)
                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'double android.location.Location.getLatitude()' on a null object reference
                  at uk.co.appoly.arcorelocation.LocationScene.refreshAnchorsIfRequired(LocationScene.java:137)
                  at uk.co.appoly.arcorelocation.LocationScene.processFrame(LocationScene.java:117)
                  at uk.co.appoly.sceneform_example.LocationActivity.lambda$onCreate$1$LocationActivity(LocationActivity.java:164)
                  at uk.co.appoly.sceneform_example.LocationActivity$$Lambda$1.onUpdate(Unknown Source)
                  at com.google.ar.sceneform.Scene.dispatchUpdate(Unknown Source)
                  at com.google.ar.sceneform.SceneView.doFrame(Unknown Source)
                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:925)
                  at android.view.Choreographer.doCallbacks(Choreographer.java:702)
                  at android.view.Choreographer.doFrame(Choreographer.java:635)
                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
                  at android.os.Handler.handleCallback(Handler.java:751)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
                  at android.os.Looper.loop(Looper.java:154)
                  at android.app.ActivityThread.main(ActivityThread.java:6692)
                  at java.lang.reflect.Method.invoke(Native Method)
                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
`

Your example does not show any marker as well. This exception is always caught multiple times.

**Comment by johnwedgbury** [comment]
Could you try updating your build.grade to use version 1.0.5, and see if the problem persists?

**Comment by codefluencer** [comment]
The examples are working again, but my problem still persists, I'll send you my code via email in couple of hours.

**Comment by codefluencer** [comment]
Was a bug on my side, sorry for bothering.
